### ISSUE TITLE
Construct_word_embedding_table: ZeroDivisionError

### ISSUE THREAD

**Issue by Tomas-Jelinek** [danifg/Left2Right-Pointer-Parser#1]
Hello,
I get a "zero division error" while training on my data (Prague Dependency Treebank) with wang2vec embeddings. Can you guess the reason for this error?

Traceback (most recent call last):
  File "scripts/L2RParser.py", line 576, in <module>
    main()
  File "scripts/L2RParser.py", line 205, in main
    word_table = construct_word_embedding_table()
  File "scripts/L2RParser.py", line 170, in construct_word_embedding_table
    scale = np.sqrt(3.0 / word_dim)
ZeroDivisionError: float division by zero

Thanks,
Tomas Jelinek

**Comment by danifg** [comment]
It seems that you are not loading the Word Embeddings correctly. Please check that your embeddings have one of the allowed formats.
